### ISSUE TITLE
What is user story detection

### ISSUE THREAD

**Issue by danielgolden** [bwiggs/nvalt-prime#7]
> "As a user, I expect" to be able to do something.

I don't understand this features use, nor how to trigger it. What does this do, and how does it work?

**Comment by bawigga** [comment]
Hey @danielgolden, 
The idea is that you can writer user story requirements and nvalt will detect and format them appropriately. I'll try and add some more info/examples to the README.

**Comment by danielgolden** [comment]
Not sure why I came back to this, but now that I look back on this I realize that my issue was that I'd never heard of a user story at the time I created this issue. Now it makes complete sense.
